#!/usr/bin/env python3
# maelendaskra
# version 1.1
# authors: Helgi Hrafn Gunnarsson <helgi@binary.is>

from lxml.html.soupparser import fromstring

import requests

URL = 'https://m.althingi.is/maelendaskra/'

def capfirst(string):
    if len(string) == 0:
        return ''
    return string[0].upper() + string[1:]

html_goo = requests.get(URL).text

stage = fromstring(html_goo, features='html.parser').find('./body/div[2]/div[2]')

try:
    issue = stage.find('h4[@id="thingmal"]').text.replace('\r\n', ' ')
    issue_type = stage.find('p[@id="malstegund"]').text
except AttributeError:
    print('Ekkert mál í gangi')
    quit()

try:
    speaking = stage.find('p[@id="raedustoll"]/strong').tail.strip()
    speech_started = stage.find('p[@id="raedustoll"]/br').text
except AttributeError:
    speaking = None
    speech_started = None

print(capfirst(issue_type))
print(issue)
print()

if speaking:
    print('Í ræðustól: %s' % speaking)
    if speech_started:
        print(speech_started)
    print()
else:
    print('Enginn í ræðustól')
    print()

for i, node in enumerate(stage.findall('ol/li[@class="maelandi"]/strong')):

    turn = i + 1
    mp = node.text
    speech = node.tail[2:].strip().strip('.')

    print('%d. %s (%s)' % (turn, mp, speech))
